from .common.json import ModelEncoder
from .models import *

class ConsentEncoder(ModelEncoder):
    model = Consent
    properties = [
        'front_id',
        'back_id',
        'first_name',
        'last_name',
        'preferred_pronouns',
        'age',
        'birth_date',
        'phone_number',
        'email',
        'address_line_1',
        'address_line_2',
        'city',
        'state_province',
        'postal_zip_code',
        'tattoo_description',
        'tattoo_placement',
        'connection',
        'under_influence',
        'pregnant_or_nursing',
        'communicable_disease',
        'skin_conditions',
        'medical_history',
        'permanent',
        'permanent_init',
        'social_media_perm',
        'social_media_perm_init',
        'refund',
        'refund_init',
        'allergen_disclosure',
        'allergen_disclosure_init',
        'aftercare',
        'aftercare_init',
        'infection',
        'infection_init',
        'compensation',
        'compensation_init',
        'allergen_risk',
        'allergen_risk_init',
        'accurate_info',
        'accurate_info_init',
        'not_minor',
        'not_minor_init',
        'signed_date',
        'signature',
        'full_name',
        'general_date',
        'general_sig',
        'aftercare_sig',
        'aftercare_date',
        'artist_sig',
        'artist_date_signed',
        'artist_name',
        'artist_date',
        'needle_info'
    ]
