# Generated by Django 5.0 on 2024-01-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='pregnant_or_nursing',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='consentformmodel',
            name='pregnant_or_nursing',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
