# Generated by Django 5.0 on 2023-12-22 23:04

import jsignature.fields
import localflavor.us.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_id', models.FileField(upload_to='')),
                ('back_id', models.FileField(upload_to='')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('preferred_pronouns', models.CharField(choices=[('he', 'he/him'), ('she', 'she/her'), ('they', 'they/them'), ('other', 'other')], max_length=10)),
                ('age', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state_province', localflavor.us.models.USStateField(max_length=2)),
                ('postal_zip_code', localflavor.us.models.USZipCodeField(max_length=10)),
                ('tattoo_description', models.CharField(max_length=500)),
                ('tattoo_placement', models.CharField(max_length=200)),
                ('connection', models.CharField(max_length=500)),
                ('under_influence', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('pregnant_or_nursing', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('communicable_disease', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('skin_conditions', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('medical_history', models.CharField(blank=True, max_length=1000, null=True)),
                ('permanent', models.BooleanField()),
                ('permanent_init', jsignature.fields.JSignatureField()),
                ('social_media_perm', models.BooleanField()),
                ('social_media_perm_init', jsignature.fields.JSignatureField()),
                ('refund', models.BooleanField()),
                ('refund_init', jsignature.fields.JSignatureField()),
                ('allergen_disclosure', models.BooleanField()),
                ('allergen_disclosure_init', jsignature.fields.JSignatureField()),
                ('aftercare', models.BooleanField()),
                ('aftercare_init', jsignature.fields.JSignatureField()),
                ('infection', models.BooleanField()),
                ('infection_init', jsignature.fields.JSignatureField()),
                ('compensation', models.BooleanField()),
                ('compensation_init', jsignature.fields.JSignatureField()),
                ('allergen_risk', models.BooleanField()),
                ('allergen_risk_init', jsignature.fields.JSignatureField()),
                ('accurate_info', models.BooleanField()),
                ('accurate_info_init', jsignature.fields.JSignatureField()),
                ('not_minor', models.BooleanField()),
                ('not_minor_init', jsignature.fields.JSignatureField()),
                ('signed_date', models.DateField()),
                ('signature', jsignature.fields.JSignatureField()),
            ],
        ),
        migrations.RenameModel(
            old_name='ConsentFormModel',
            new_name='ConsentFormPDF',
        ),
    ]
