# Generated by Django 5.0 on 2024-01-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_consent_pregnant_or_nursing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='back_id',
            field=models.FileField(upload_to='temp_id_photos/'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='front_id',
            field=models.FileField(upload_to='temp_id_photos/'),
        ),
    ]
