# Generated by Django 5.0 on 2023-12-22 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_consentform_rename_consentformmodel_consentformpdf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsentForm',
            new_name='Consent',
        ),
    ]
