# Generated by Django 5.0 on 2024-01-10 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_minor_consent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Minor_Consent',
            new_name='MinorConsent',
        ),
    ]
