# Generated by Django 5.0 on 2024-02-08 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_rename_minor_consent_minorconsent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsentFormModel',
        ),
    ]
