# Generated by Django 5.0 on 2024-02-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_delete_consentformmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
