# Generated by Django 5.0 on 2024-02-14 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signature',
            old_name='created_at',
            new_name='signed_at',
        ),
        migrations.RemoveField(
            model_name='consentpdf',
            name='signed_at',
        ),
    ]
